version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dailylog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - JWT_SECRET=your_jwt_secret_key_here
      - DSN=host=db user=postgres password=postgres dbname=dailylog port=5432 sslmode=disable
    ports:
      - "3000:3000"

volumes:
  pgdata:
