
---

    # GitHub Actions CI - `.github/workflows/ci.yml`
    
    ```yaml
    name: CI
    
    on:
      push:
        branches: [main]
      pull_request:
        branches: [main]
    
    jobs:
      build-and-test:
        runs-on: ubuntu-latest
    
        services:
          postgres:
            image: postgres:15
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: dailylog
            ports:
              - 5432:5432
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
    
        steps:
          - uses: actions/checkout@v3
    
          - name: Set up Go
            uses: actions/setup-go@v4
            with:
              go-version: 1.20
    
          - name: Wait for Postgres
            run: |
              until pg_isready -h localhost -p 5432; do
                echo "Waiting for Postgres..."
                sleep 2
              done
    
          - name: Install dependencies
            run: go mod download
    
          - name: Run tests
            env:
              DSN: host=localhost user=postgres password=postgres dbname=dailylog port=5432 sslmode=disable
              JWT_SECRET: testsecret
            run: go test ./internal/api/...
    